# Generated by Django 3.1 on 2020-09-03 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200903_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='ingridient',
            new_name='ingredient',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='main.RecipeIngredients', to='main.Ingredient'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipe'),
        ),
    ]
