# Generated by Django 3.1 on 2020-09-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200903_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredients',
            name='unit',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='шт', max_length=63, verbose_name='Единица измеерния'),
            preserve_default=False,
        ),
    ]
